### ISSUE TITLE
MiniEffects 1.12.2 version work not with one of my other Mods. 

### ISSUE THREAD

**Issue by Titoo8899** [Snownee/MiniEffects#1]
![2021-07-18_20 42 07](https://user-images.githubusercontent.com/42325138/126078753-711afa70-3664-4d33-b123-6410e4a5f508.png)

This is the Picture what the Problem show. The Effect is normal and not Mini what you have in your GUI and this all the time. 
Please check this Link with all my mods what active was and fix the Compatible of the problem mod with your.#

Link to my Modpack: https://drive.google.com/file/d/1mRrz95jipBnt65Jra409YP87hh_CmkTm/view?usp=sharing

I have play with your mod only and it work but I have no idear what Mod from my Pack not compatible is with your mod.

**Comment by Snownee** [comment]
fixed in 1.0.1
