### ISSUE TITLE
Effects still appear on the right they are just hidden but cause serious issues in using JEI

### ISSUE THREAD

**Issue by mcdodge34** [Snownee/MiniEffects#3]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

4.1.0

### Modloader version

Forge 40.1.80

### Modpack info

Unlisted Private

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

This is a serious problem, you just hide the effects but not completely like it should be done, here's a video explaining and showing the exact problem, its a neat idea but it needs to be improved.

https://www.youtube.com/watch?v=y0bWpzdS7pI

**Comment by Snownee** [comment]
https://github.com/MehVahdJukaar/JustEnoughEffectDescriptions/issues/11 this?

**Comment by mcdodge34** [comment]
Will try without that mod, I need this mod because some effects aren't described, like Farmers Delights have serious lack of description of some of their effects, they just say Beneficial.

And strike, its a problem with Just Enough Effects Descriptions then
