### ISSUE TITLE
请求配置文件提供移动UI的选项

### ISSUE THREAD

**Issue by ukmojb** [Snownee/MiniEffects#7]
### Mod loader

Forge

### Minecraft version

1.12.2

### Mod version

1.0.1

### Modloader version

Forge 14.23.5.2860 

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

模组将药水效果折叠之后，与其他模组的UI发生重叠，所以请问能不能在配置文件给出移动UI的方法？

**Comment by Snownee** [comment]
和什么模组发生怎样的重叠？

**Comment by ukmojb** [comment]
https://www.mcmod.cn/class/1088.html
和这个模组的UI发生了重叠，具体是这样的[https://attachment.mcbbs.net/data/myattachment/forum/202302/11/202133z86q9z8z9a0fvzjx.png](url)

**Comment by ukmojb** [comment]
图片我发在这个帖子里面，由于我现在是手机，没有办法上传图片https://www.mcbbs.net/thread-1427068-1-1.html

**Comment by Snownee** [comment]
效果展开后的情况是什么？

**Comment by ukmojb** [comment]
展开之后是会相应的往左移，但是展开前看着特别怪

**Comment by Snownee** [comment]
好的，有时间我会添加的

**Comment by ukmojb** [comment]
十分感谢
