### ISSUE TITLE
UI问题

### ISSUE THREAD

**Issue by ukmojb** [Snownee/MiniEffects#9]
### Mod loader

Forge

### Minecraft version

1.12.2

### Mod version

1.10

### Modloader version

Forge 14.23.5.2860

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

BUG：
移动UI后鼠标移动到移动后好UI上时，会一直闪烁

移动前
https://user-images.githubusercontent.com/105061290/219830644-d92fb295-7499-477d-9760-57792a03fe44.mp4

移动后
https://user-images.githubusercontent.com/105061290/219830651-0152a9fe-9dd1-4d5a-a878-ea0ce4bd3431.mp4

功能请求：
1.能不能让药水效果折叠之后不会再让jei的物品移动，不然屏幕会莫名的空一大块
![2023-02-18 (1)](https://user-images.githubusercontent.com/105061290/219830695-9539b935-b433-447b-8a96-82abd4b5b0e7.png)
![2023-02-18 (2)](https://user-images.githubusercontent.com/105061290/219830697-0f922e98-c17e-46bf-85f6-cf611d8d25c9.png)

2.能不能再提供移动药水效果的配置
![2023-02-18](https://user-images.githubusercontent.com/105061290/219830669-68c42b2b-1803-4cd2-aa5a-6a00741c7a72.png)

**Comment by Snownee** [comment]
那个位移设置的意思是让你把折叠后的图标移动到其他模组修改过的相应位置，不是让你移动到任意位置

**Comment by ukmojb** [comment]
听不懂

**Comment by Snownee** [comment]
听不懂

**Comment by ukmojb** [comment]
其他模组修改过的相应位置是什么意思？

**Comment by Snownee** [comment]
![image](https://user-images.githubusercontent.com/16059084/219838354-f826d6d8-2d8a-483a-b30c-851e71ae0a74.png)

**Comment by ukmojb** [comment]
把折叠后的图标移动到那边？

**Comment by Snownee** [comment]
对

**Comment by ukmojb** [comment]
改位置之后的确不闪烁了
还有请问能不能让左边那一排药水效果移动？
超出屏幕挺难受的）

**Comment by Snownee** [comment]
太麻烦，懒得改了
